import 'package:stock_app/util/globals.dart';

String emailString = "Email";
String passwordString = lang == 'en' ? "Password" : "Mật khẩu";
String forgotPassString = lang =='en' ? "Forgot Password?" : "Quên mật khẩu?";
String loginString = lang == 'en' ? "Login" : "Đăng nhập";
String doNotHaveAccountString = lang == 'en' ? 'Don\'t have an account?' : "Chưa có tài khoản?";
String registerString = lang == 'en' ? "Register" : "Đăng ký";
String userOrEmailString = lang == 'en' ? "Username or email" : "Tên đăng nhập hoặc email";
String usernameString = lang == 'en' ? "Username" : "";
String registerCapitalString = lang == 'en' ? "REGISTER" : "";
String registerInstructionString = lang == 'en' ? 'Enter your information to continue, we will send you OTP to verify.' : "";
String requestOtp = lang == 'en' ? "Request OTP" : "";
String alreadyHaveAccount = lang == 'en' ? 'Already have an account?' : "";
String verificationString = lang == 'en' ? "Verification" : "";
String verificationInstructionString = lang == 'en' ? "Please enter the 4 digit code sent to \n Email@gmail.com" : "";
String doNotReceiveString = lang == 'en' ? "Don't receive the OTP?" : "";
String tryAgainString = lang == 'en' ? "Try again in " : "";
String resendString = lang == 'en' ? "Resend" : "";
String verifyString = lang == 'en' ? "Verify" : "";
String stockString = lang == 'en' ? 'Stocks' : "";
String editString = lang == 'en' ? 'Edit' : "";
String searchString = lang == 'en' ? 'Search' : "";
String openString = lang == 'en' ? 'Open' : "";
String highString = lang == 'en' ? 'High' : "";
String lowString = lang == 'en' ? 'Low' : "";
String nameString = lang == 'en' ? 'Your Name' : "";
String joinGroupString = lang == 'en' ? 'Join Group' : "";
String addToListString = lang == 'en' ? 'Add to list' : "";
String deleteFromListString = lang == 'en' ? 'Delete from list' : "";
String predictString = lang == 'en' ? 'Predict' : "";
String groupString = lang == 'en' ? 'Group' : "";
String homeString = lang == 'en' ? "Home" : "";
String newsString = lang == 'en' ? "News" : "";